# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#package-ecosystem-

version: 2
updates:
  - package-ecosystem: bun
    directory: .github/actions/rune
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directories:
      - rune-rs
      - rune-rs/*
    schedule:
      interval: weekly
  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: rune-cli
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: rust-toolchain
    directory: rune-rs
    schedule:
      interval: weekly
