name: Release to Pipy and Zed's store

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release-pypy:
    name: Release to Pypi
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/mistral-vibe
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5

      - name: Install dependencies
        run: uv sync --locked --dev

      - name: Build package
        run: uv build

      - name: Upload artifacts
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
        with:
          name: dist
          path: dist/

      - name: Publish distribution to PyPI
        if: github.repository == 'mistralai/mistral-vibe'
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0

  release-zed-extension:
    name: Release Zed Extension
    runs-on: ubuntu-latest
    if: github.repository == 'mistralai/mistral-vibe'
    permissions:
      contents: read
    environment:
      name: zed
    steps:
      - uses: huacnlee/zed-extension-action@8cd592a0d24e1e41157740f1a529aeabddc88a1b # v2
        with:
          extension-name: mistral-vibe
          push-to: mistralai/zed-extensions
        env:
          COMMITTER_TOKEN: ${{ secrets.ZED_EXTENSION_GITHUB_TOKEN }}
